- name: Install and configure Nginx
  hosts:  
  become: yes
  vars:
    nginx_package: nginx
    nginx_port: 80
  tasks:
    - name: Install Nginx
      apt:
        name: "{{ nginx_package }}"
        state: present
    - name: Ensure Nginx is running
      service:
        name: "{{ nginx_package }}"
        state: started
        enabled: yes